### ISSUE TITLE
Incoming Health from Heals

### ISSUE THREAD

**Issue by dinotheextinct** [AzeriteTeam/AzeriteUI_Classic#23]
**Is your feature request related to a problem? Please describe.**
It would be pretty mandatory to have some kind of incoming heals visuallized for your target, party and raidframes. In order to estimate what kind of heal to use in a given scenario its not always practical to look for a calculator and do the math of target hp and your spells actual healing.

**Describe the solution you'd like**
An indication of incoming heals you cast yourself on all frames mentioned. This would have to take into account your +healing and talents. Maybe there are other addons already providing this info which you just need to integrate somehow?

**Comment by goldpaw** [comment]
Heal prediction is not a part of the classic API, nor was it part of the game in vanilla. It requires everybody in the raid to be using the same addon that syncs events and heals between them, which is outside the scope of what this UI sets out to do. 

It would be unrealistic to expect a whole raid to use this UI, especially since only a couple of hundred people in classic appear to be using it in the first place. So unless some other addon provides a very easy to work with API without resulting to a ton of ace3 libraries, I probably won't be adding this.

**Comment by lithammer** [comment]
The entire raid wouldn't have to use this UI, specifically. They just need to use an addon or UI that integrates with something like [LibHealComm-4.0](https://www.wowace.com/projects/libhealcomm-4-0). And from what I could tell, they only depend on [LibStub](https://www.wowace.com/projects/libstub) and [CallbackHandler-1.0](https://www.wowace.com/projects/callbackhandler). Which are relatively small.

**Comment by goldpaw** [comment]
No, I'm not going to include or support anything that relies on Ace3 or other external LibStub-based library sets.
